spring:
  application:
    name: ChatApp

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver

#########################################
#  auto refresh (server restart skip)
#########################################
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false

#########################################
#  file upload available size
#########################################
  servlet:
    multipart:
      location: ${user.dir}/uploads/    # default /tmp
      file-size-threshold: 100          # default 0KB
      max-file-size: 500MB              # default 1MB
      max-request-size: 500MB           # default 10MB

#########################################
#  reids
#########################################
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379} # localhost:6379 는 기본값, 로컬에서는 설정 생략 가능
    password: ${REDIS_PASSWORD}

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate.SQL: DEBUG

#########################################
#  jwt
#########################################
jwt:
  secret: ${JWT_SECRET}

  access:
    expiration: 20000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

#########################################
#  server
#########################################
server:
  tomcat:
    threads:
      max: 200  # 최대 스레드 증가
      min-spare: 50
    accept-count: 500  # 대기 큐 크기 증가

#########################################
#  actuator
#########################################
management:
  endpoints.web.exposure.include: health, info, prometheus